name= input("Enter your Name : ")
age= input("Enter your age: ")
gpa= input("Enter your GPA: ")
print("Student Information")
print("-----------------")
print("Name : "+ name)
print("Age : " +age)
print("GPA : " + gpa)